### ISSUE TITLE
Issue parsing Lileas NPC Shop

### ISSUE THREAD

**Issue by eotetb** [exectails/MabiPale2#15]
The parser has an issue parsing the op `0x715E`. I suspect this is because of her special Jousting Point shop. The following error occurs.

```
Error: System.Exception: Expected Long, got Bin.
   at MabiPale2.Shared.Packet.GetLong()
   at MabiPale2.Plugins.PacketAnalyzer.Packets.NpcShop.AnalyzePacket(PalePacket palePacket)
   at MabiPale2.Plugins.PacketAnalyzer.FrmInfo.OnSelected(PalePacket palePacket)
```

**Comment by exectails** [comment]
Thanks for the report. The issue was that Lileas' shop has items with upgrade effects, which Pale didn't parse. This was fixed in the latest release.
