### ISSUE TITLE
Error when reading packet

### ISSUE THREAD

**Issue by ghost** [exectails/MabiPale2#6]
```
************** Exception Text **************
System.ArgumentOutOfRangeException: Index and count must refer to a location within the buffer.
Parameter name: bytes
   at System.Text.UTF8Encoding.GetString(Byte[] bytes, Int32 index, Int32 count)
   at MabiPale2.Shared.Packet.GetString()
   at MabiPale2.Shared.Packet.ToString()
   at MabiPale2.Shared.PalePacket.ToString()
   at MabiPale2.FrmMain.LstPackets_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ListView.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

Packet:

```
Send@06:22:35.442 0000AA4100100000000020B6070200030000005E01000621EC12
```

**Comment by exectails** [comment]
That packet is perfectly valid, and can be read using the Packet Parser. It also doesn't include a string, which is why I don't see how it would cause the exception.

**Comment by ImaBrokeDude** [comment]
Weird I get this with Version 2.9.0 when trying to read that exact packet. I will try with the analyzer.

**Comment by exectails** [comment]
The reason this failed was that the packet was simply invalid. I don't know how that happened, but Pale's behavior was correct. The problem would probably lie with Morrighan if anything, but since this never came up again, I'll assume it was either a one-time glitch or the issue was fixed.
